export { default as 'Home'} from './Home';
export { default as 'Profile'} from './Profile';
export { default as 'Friends'} from './Friends';
export { default as 'Groups'} from './Groups';
export { default as 'Chats'} from './Chats';
export { default as 'Pages'} from './Pages';
export { default as 'ProfileSettings'} from './ProfileSettings';
export { default as 'CreatePost'} from './CreatePost';
export { default as 'EditPost'} from './EditPost';